account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/Account_Team_Member_History__c.object-meta.xml
<CustomObject>
    <description>Stores a complete snapshot of Account Team Members associated with an Account, for both active and inactive (history) assignments.</description>
    <label>Account Team Member History</label>
    <nameField>
        <label>Account Team Member History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Team Member Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Account this record is associated with</description>
    <inlineHelpText>Associated Account Record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Member Histories</relationshipLabel>
    <relationshipName>Account_Team_Member_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Account_Access__c.field-meta.xml
<CustomField>
    <fullName>Account_Access__c</fullName>
    <description>Level of access the user had to the Account in their Team Member role. Populated via automation from the AccountAccessLevel field on the Account Team Member record.</description>
    <label>Account Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Active_From__c.field-meta.xml
<CustomField>
    <fullName>Active_From__c</fullName>
    <description>Date when the User became an active Team Member to the Account</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Active_To__c.field-meta.xml
<CustomField>
    <fullName>Active_To__c</fullName>
    <description>Date the User stopped being an associated Team Member for the Account</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user who added the Team Member. Used in conjunction with the Active From date field to create a clear who/when audit line for Account Team Member additions</description>
    <label>Added By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Member_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Case_Access__c.field-meta.xml
<CustomField>
    <fullName>Case_Access__c</fullName>
    <description>Level of access the user had to the Cases associated to the Account in their Team Member role. Populated via automation from the CaseAccessLevel field on the Account Team Member record.</description>
    <label>Case Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Contact_Access__c.field-meta.xml
<CustomField>
    <fullName>Contact_Access__c</fullName>
    <description>Level of access the user had to the Contact associated to the Account in their Team Member role. Populated via automation from the ContactAccessLevel field on the Account Team Member record.</description>
    <label>Contact Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Opportunity_Access__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Access__c</fullName>
    <description>Level of access the user had to the Opportunities tied to the Account in their Team Member role. Populated via automation from the OpportunityAccessLevel field on the Account Team Member record.</description>
    <label>Opportunity Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Removed_By__c.field-meta.xml
<CustomField>
    <fullName>Removed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user who removed the Team Member. Used in conjunction with the Active To date field to create a clear who/when audit line for Account Team Member removals</description>
    <label>Removed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Member_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the Team Member related to the account.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User record of the assigned Team Member for the Account</description>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Member_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Team_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Role__c</fullName>
    <description>Identifies the role the team member carried during their association with the Account. Populated via automation from the Team Role picklist on the Account Team Member object</description>
    <label>Team Member Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

account-team-history/force-app/main/default/classes/services/AccountTeamMemberHistoryService.cls
//Primary processing class for the Account Team Member History custom object. Handles all logic relating to the creation and update of
//the Account Team Member History records. These methods are invoked from the AccountTeamMemberTriggerHandler class, which in turn is
//invoked from the AccountTeamMemberTrigger trigger.
public with sharing class AccountTeamMemberHistoryService {
    //Dependency injection of UserSelector to allow for easier unit testing and mocking
    private UserSelector userSelector;
    private AccountTeamMemberHistorySelector atmHistorySelector;
    
    //Base constructor for use in production code; initializes UserSelector dependency
    public AccountTeamMemberHistoryService() {
        this.userSelector = new UserSelector();
        this.atmHistorySelector = new AccountTeamMemberHistorySelector();
    }

    /**
     * Constructor with dependency injection for testing - only visible in testing context
     * @param selector Mock selector to be used in place of the real UserSelector
     */
    @TestVisible
    private AccountTeamMemberHistoryService(UserSelector mockUserSelector, AccountTeamMemberHistorySelector mockAccountTeamMemberHistorySelector) {
        this.userSelector = mockUserSelector;
        this.atmHistorySelector = mockAccountTeamMemberHistorySelector;
    }

    /** 
     * Creates Account Team Member History records for each AccountTeamMember record that was inserted as part of the trigger context.
     * @param newAccountTeamMemberRecords List of newly inserted AccountTeamMember records, passed from AccountTeamMemberTriggerHandler
     * @see AccountTeamMemberTriggerHandler.afterInsert()
    */
    public List<Account_Team_Member_History__c> createHistoryRecords(List<AccountTeamMember> newAccountTeamMemberRecords) {
        //Instantiate set of UserIds, iterate over each AccountTeamMember record and pull out the User ID for that record
        //These ids will be used to fetch user records which will in turn be used during the creation to set context-specific names
        Set<Id> userIds = new Set<Id>();
        for(AccountTeamMember atm : newAccountTeamMemberRecords) userIds.add(atm.UserId);
        //Fetch user records associated with the triggering AccountTeamMember record via selector
        Map<Id, User> userMap = this.userSelector.getUsersByIds(userIds);

        //Init list of AccountTeamMemberHistory (atmHistory for short) records to be created
        List<Account_Team_Member_History__c> atmHistoryRecordsToInsert = new List<Account_Team_Member_History__c>();
        //Iterate over each AccountTeamMember record in the trigger context and set up a new atmHistory record using its data
        for(AccountTeamMember atm : newAccountTeamMemberRecords) {
            //Init empty atmHistory record
            Account_Team_Member_History__c atmHistoryRecord = new Account_Team_Member_History__c();
            
            //Get the User Name of the User associated with the AccountTeamMember record from the previously fetched userMap
            String userName = userMap.containsKey(atm.UserId) ? userMap.get(atm.UserId).Name : 'Unknown User';

            //Populate atmHistory record fields\\
            atmHistoryRecord.Name = userName + ' - ' + atm.TeamMemberRole;
            atmHistoryRecord.Account__c = atm.AccountId;
            atmHistoryRecord.Team_Member__c = atm.UserId;
            atmHistoryRecord.Team_Member_Role__c = atm.TeamMemberRole;
            atmHistoryRecord.Status__c = 'Active';
            atmHistoryRecord.Active_From__c = System.today();
            atmHistoryRecord.Account_Access__c = atm.AccountAccessLevel;
            atmHistoryRecord.Case_Access__c = atm.CaseAccessLevel;
            atmHistoryRecord.Opportunity_Access__c = atm.OpportunityAccessLevel;
            atmHistoryRecord.Contact_Access__c = atm.ContactAccessLevel;
            atmHistoryRecord.Added_By__c = atm.CreatedById;
            atmHistoryRecord.AccountTeamMemberId__c = atm.Id;

            //Add instantiated atmHistory record to the list of records to be inserted
            atmHistoryRecordsToInsert.add(atmHistoryRecord);
        }

        //Defensive check: only attempt to insert if there are records to insert
        if(!atmHistoryRecordsToInsert.isEmpty()) {
            insert atmHistoryRecordsToInsert;
            return atmHistoryRecordsToInsert;
        } else {
            return new List<Account_Team_Member_History__c>();
        }
    }


    /**
     * Updates Account Team Member History records tied to the deleted AccountTeamMember records to track inactivation of the Account Team Member.
     * @param deletedAccountTeamMemberRecords List of deleted AccountTeamMember records, passed from AccountTeamMemberTriggerHandler
     * @see AccountTeamMemberTriggerHandler.afterDelete()
     */
    public void inactivateHistoryRecords(List<AccountTeamMember> deletedAccountTeamMemberRecords) {
        //Instantiate set of ids and populate with the associated AccountTeamMember record ids from the deleted records
        //then use the AccountTeamMemberHistorySelector to fetch the associated Account Team Member History records
        Set<Id> atmIds = new Set<Id>();
        for(AccountTeamMember atm : deletedAccountTeamMemberRecords) {
            atmIds.add(atm.Id);
        }
        Map<Id, Account_Team_Member_History__c> atmHistoryRecords = this.atmHistorySelector.getAccountTeamMemberHistoryByAtmIds(atmIds);

        //Instantiate list to hold atmHistory records to be updated
        List<Account_Team_Member_History__c> atmHistoryRecordsToUpdate = new List<Account_Team_Member_History__c>();
        //Iterate over each fetched atmHistory record and update it
        for(Account_Team_Member_History__c atmHistoryRecord : atmHistoryRecords.values()) {
            atmHistoryRecord.Status__c = 'Inactive';
            atmHistoryRecord.Active_To__c = System.today();
            atmHistoryRecord.Removed_By__c = UserInfo.getUserId();

            //Add updated record to the list of records to be updated
            atmHistoryRecordsToUpdate.add(atmHistoryRecord);
        }

        //Defensive check: only attempt to update if there are records to update
        if(!atmHistoryRecordsToUpdate.isEmpty()) {
            update atmHistoryRecordsToUpdate;
        }
    }
}