account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/Account_Team_Member_History__c.object-meta.xml
<CustomObject>
    <description>Stores a complete snapshot of Account Team Members associated with an Account, for both active and inactive (history) assignments.</description>
    <label>Account Team Member History</label>
    <nameField>
        <label>Account Team Member History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Team Member Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Account this record is associated with</description>
    <inlineHelpText>Associated Account Record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Member Histories</relationshipLabel>
    <relationshipName>Account_Team_Member_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Active_To__c.field-meta.xml
<CustomField>
    <fullName>Active_To__c</fullName>
    <description>Date the User stopped being an associated Team Member for the Account</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Removed_By__c.field-meta.xml
<CustomField>
    <fullName>Removed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the user who removed the Team Member. Used in conjunction with the Active To date field to create a clear who/when audit line for Account Team Member removals</description>
    <label>Removed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Member_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

account-team-history/force-app/main/default/objects/Account_Team_Member_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the Team Member related to the account.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

account-team-history/force-app/main/default/classes/selectors/AccountTeamMemberHistorySelector.cls
public virtual with sharing class AccountTeamMemberHistorySelector {

    //Default constructor
    public AccountTeamMemberHistorySelector() {}

    //Field set defining which Account Team Member History fields to retrieve in queries. Can be modified to add/remove fields as needed
    private static final List<Schema.SObjectField> ATM_HISTORY_FIELDS = new List<Schema.SObjectField>{
        Account_Team_Member_History__c.Id,
        Account_Team_Member_History__c.Account__c,
        Account_Team_Member_History__c.Status__c,
        Account_Team_Member_History__c.Active_To__c,
        Account_Team_Member_History__c.Removed_By__c
    };

    /**
     * Helper method to convert the ATM_HISTORY_FIELDS list into a comma-separated string for use in dynamic SOQL queries
     * @return String Comma-separated string of Account Team Member History field names
     */
    private static String getFieldString() {
        List<String> fieldNames = new List<String>();
        for (Schema.SObjectField field : ATM_HISTORY_FIELDS) {
            fieldNames.add(field.getDescribe().getName());
        }
        return String.join(fieldNames, ', ');
    }

    /** 
     * Fetches Account Team Member History records for the given set of related Account Team Member IDs.
     * 
     * @param atmHistoryIds Set of Account Team Member IDs for which to fetch records
     * @return Map<Id, Account_Team_Member_History__c> Map of Account Team Member History records keyed by their IDs
    */
    public virtual Map<Id, Account_Team_Member_History__c> getAccountTeamMemberHistoryByAtmIds(Set<Id> atmIds) {
        //Defensive check - if atmIds is null or empty, return empty list
        if (atmIds == null || atmIds.isEmpty()) {
            return new Map<Id, Account_Team_Member_History__c>();
        }
        
        //Otherwise, build queryString from defined list of fields and run query fetching Account Team Member History record for the given atmIds
        //This will either return a map of Account Team Member History records, a empty map if no records found, or a QueryException if an error occurs
        //Database.query() returns a list of sObjects. To send it to a map, we have to explicitly cast it to List and then to Map
        String query = 'SELECT ' + getFieldString() + ' FROM Account_Team_Member_History__c WHERE AccountTeamMemberId__c IN :atmIds';
        return new Map<Id, Account_Team_Member_History__c>((List<Account_Team_Member_History__c>)Database.query(query));
    }
}